#!/bin/bash -e

function usage { cat <<EOF
USAGE: $0 bucket
  example: $0 23234-bigbucket-us-west-1

  Environment variables required: HYPERKUBE, INTERNAL_TLD and REGION.
  example:
    HYPERKUBE=gcr.io/google_containers/hyperkube:v1.2.4 \
    INTERNAL_TLD=test.k8s \
    REGION=us-west-1 \
    $0 23234-bigbucket-us-west-1
EOF
  exit 1
}

function cleanup {
  rm -rf "$TMP"
  echo "✓ Deleted temp working directory $TMP"
}

function error {
  echo "✗ Error from s3-cp on line $1"'!'
  exit 1
}
trap 'error ${LINENO}' ERR

# check parameters
BUCKET=$1
[ -z "$BUCKET" ] && usage

# assert environment variables
[ -z "$HYPERKUBE" ] && usage
[ -z "$INTERNAL_TLD" ] && usage
[ -z "$REGION" ] && usage

# print environment and parameter
echo "❤ s3-cp using these settings"
echo envvar HYPERKUBE=${HYPERKUBE}
echo envvar INTERNAL_TLD=${INTERNAL_TLD}
echo envvar REGION=${REGION}
echo parameter BUCKET=${BUCKET}
echo "✓ Print environment variables and parameters success"

set -o nounset
set -o pipefail

# directories
CFSSL=.cfssl

# verify directories exist
[ -d "$CFSSL" ] || (echo "✗ $CFSSL doesn't exist" && exit 1)

# cp tls assets
echo "❤ Copy tls assets to s3 ${BUCKET}"
aws s3 cp .cfssl s3://${BUCKET}/ssl --recursive --exclude "*" --include "*.tar" \
  --region ${REGION}
echo "✓ tls copy success"
