#!/bin/bash -eux

[ -z "$OUTDIR" ] && { echo "Need to set OUTDIR"; exit 1; }
[ -z "$NAME" ] && { echo "Need to set NAME"; exit 1; }
[ -z "$CA_PATH" ] && { echo "Need to set CA_PATH"; exit 1; }
[ -z "$MASTER_ELB_URL" ] && { echo "Need to set MASTER_ELB_URL"; exit 1; }
[ -z "$ADMIN_CERT_PATH" ] && { echo "Need to set ADMIN_CERT_PATH"; exit 1; }
[ -z "$ADMIN_KEY_PATH" ] && { echo "Need to set ADMIN_KEY_PATH"; exit 1; }

[ -d ${OUTDIR} ] || mkdir ${OUTDIR}

cat << EOF > ${OUTDIR}/kubeconfig
kubectl config set-cluster cluster-${NAME} \
  --embed-certs=true \
  --server=https://${MASTER_ELB_URL} \
  --certificate-authority=${CA_PATH}

kubectl config set-credentials admin-${NAME} \
  --embed-certs=true \
  --certificate-authority=${CA_PATH} \
  --client-key=${ADMIN_KEY_PATH} \
  --client-certificate=${ADMIN_CERT_PATH}

kubectl config set-context ${NAME} \
  --cluster=cluster-${NAME} \
  --user=admin-${NAME}

kubectl config use-context ${NAME}

EOF

kubectl config set-cluster cluster-${NAME} \
  --embed-certs=true \
  --server=https://${MASTER_ELB_URL} \
  --certificate-authority=${CA_PATH}

kubectl config set-credentials admin-${NAME} \
  --embed-certs=true \
  --certificate-authority=${CA_PATH} \
  --client-key=${ADMIN_KEY_PATH} \
  --client-certificate=${ADMIN_CERT_PATH}

kubectl config set-context ${NAME} \
  --cluster=cluster-${NAME} \
  --user=admin-${NAME}

kubectl config use-context ${NAME}
