#!/bin/bash -eu

echo $DIR_KUBECONFIG
echo $CLUSTER_NAME
echo $DIR_SSL


CA_PATH=$DIR_SSL/ca.pem
MASTER_ELB_URL=`terraform output external-elb`
ADMIN_CERT_PATH=$DIR_SSL/k8s-admin.pem
ADMIN_KEY_PATH=$DIR_SSL/k8s-admin-key.pem


mkdir -p $DIR_KUBECONFIG


cat << EOF > ${DIR_KUBECONFIG}/kubeconfig
kubectl config set-cluster cluster-${CLUSTER_NAME} \
  --embed-certs=true \
  --server=https://${MASTER_ELB_URL} \
  --certificate-authority=${CA_PATH}

kubectl config set-credentials admin-${CLUSTER_NAME} \
  --embed-certs=true \
  --certificate-authority=${CA_PATH} \
  --client-key=${ADMIN_KEY_PATH} \
  --client-certificate=${ADMIN_CERT_PATH}

kubectl config set-context ${CLUSTER_NAME} \
  --cluster=cluster-${CLUSTER_NAME} \
  --user=admin-${CLUSTER_NAME}

kubectl config use-context ${CLUSTER_NAME}
EOF

kubectl config set-cluster cluster-${CLUSTER_NAME} \
  --embed-certs=true \
  --server=https://${MASTER_ELB_URL} \
  --certificate-authority=${CA_PATH}

kubectl config set-credentials admin-${CLUSTER_NAME} \
  --embed-certs=true \
  --certificate-authority=${CA_PATH} \
  --client-key=${ADMIN_KEY_PATH} \
  --client-certificate=${ADMIN_CERT_PATH}

kubectl config set-context ${CLUSTER_NAME} \
  --cluster=cluster-${CLUSTER_NAME} \
  --user=admin-${CLUSTER_NAME}

kubectl config use-context ${CLUSTER_NAME}
