#!/bin/bash -eux


echo $DIR_SSL
echo $CLUSTER_NAME
echo $AWS_EC2_KEY_PATH
BASTION_IP=`terraform output bastion-ip`


function error {
  echo "✗ Error on line $1"'!'
  exit 1
}
trap 'error ${LINENO}' ERR

# setup port forwarding
#
ssh-keyscan ${BASTION_IP}
ssh -o StrictHostKeyChecking=no -i ${AWS_EC2_KEY_PATH} -nNT -L 8888:pki.${INTERNAL_TLD}:8888 core@${BASTION_IP} &
SSH_PID=$!

function finish {
  [ -z ${SSH_PID} ] || kill ${SSH_PID}
}
trap finish EXIT

# test cfssl connection -- retry until up
#
until printf "." && curl -d '{"label":"primary"}' http://localhost:8888/api/v1/cfssl/info &>/dev/null
do sleep 2.5; done; echo "✓"

function csr {
  cat <<EOF
{"CN":"$1","hosts":[""],"key":{"algo":"rsa","size":2048}}
EOF
}


function generate {

  CN=$1
  PROFILE=$2

  echo "$(csr $CN)" \
    | cfssl gencert \
      -remote=localhost:8888 \
      -profile=$PROFILE  - \
    | cfssljson -bare $CN

  chmod 0644 $CN.pem ${CN}-key.pem

}

mkdir -p $DIR_SSL && cd $DIR_SSL

generate k8s-admin client
