#!/bin/bash -ex

CDIR=$(cd `dirname "$0"` && pwd)
source $CDIR/utils

NAMESPACE=${NAMESPACE:-kube-system}
KUBECTL="kubectl --namespace=\"${NAMESPACE}\""

OBJECTS="
service/heapster
service/kube-dns
deploy/heapster-v1.3.0
deploy/kube-dns
deploy/kube-dns-autoscaler
deploy/kibana-logging
rc/elasticsearch-logging-v1
statefulset/elasticsearch-logging
daemonset/fluentd
"

for object in ${OBJECTS}; do
  eval "${KUBECTL} delete --ignore-not-found --now \"${object}\""
done
