#!/bin/bash

if [ "$#" -lt 2 ]; then
  echo not enough args
  exit 1
fi

red='\e[1;31m%s\e[0m\n'
green='\e[1;32m%s\e[0m\n'
yellow='\e[1;33m%s\e[0m\n'
blue='\e[1;34m%s\e[0m\n'
magenta='\e[1;35m%s\e[0m\n'
cyan='\e[1;36m%s\e[0m\n'


TEXT=$1
shift


printf "$blue" "❤ $TEXT"

"$@"
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]
then
  printf "$green" "✓ $TEXT - SUCCESS"
else
  printf "$red" "✗ $TEXT - FAIL"
fi

echo
exit $EXIT_CODE
