#!/bin/bash -eu

source ${0%/*}/retry

echo $DIR_SSL
PKI_S3_BUCKET=`terraform output s3-bucket`
CA_PATH="s3://$PKI_S3_BUCKET/ca.pem"

mkdir -p $DIR_SSL

_retry "❤ Grabbing $CA_PATH" aws s3 cp $CA_PATH $DIR_SSL
