#!/bin/bash -e

source ${0%/*}/retry

[ -z "$OUTDIR" ] && { echo "Need to set OUTDIR"; exit 1; }
[ -z "$PKI_S3_BUCKET" ] && { echo "Need to set PKI_S3_BUCKET"; exit 1; }

CA_PATH="s3://${PKI_S3_BUCKET}/ca.pem"

[ -d ${OUTDIR} ] || mkdir ${OUTDIR}

_retry "❤ Grabbing ${CA_PATH}" aws s3 cp ${CA_PATH} ${OUTDIR}
