#!/bin/bash -eu

if ! aws iam get-user > /dev/null; then
	echo AWS_PROFILE not set or is misconfigured
	exit 3
fi

source ${0%/*}/retry

DIR_SSL=ssl

echo $DIR_SSL
PKI_S3_BUCKET=`terraform output s3-bucket`
CA_PATH="s3://$PKI_S3_BUCKET/ca.pem"

mkdir -p $DIR_SSL

_retry "❤ Grabbing $CA_PATH" aws s3 cp $CA_PATH $DIR_SSL
