#!/bin/bash -eu

ELB=$(terraform output external-elb)
export DNS_SERVICE_IP=$(terraform output dns-service-ip)
export INTERNAL_TLD=$(terraform output internal-tld)

_retry() {
  [[ -z $2 ]] && return 1
  echo -n ${1}
  until printf "." && "${@:2}" &>/dev/null; do sleep 5.2; done; echo "✓"
}

echo "❤ Polling for cluster life - this could take a minute or more"
_retry "❤ Waiting for DNS to resolve for $ELB" ping -c1 "$ELB"
_retry "❤ Curling apiserver external elb" curl --insecure --silent "https://$ELB"
_retry "❤ Trying to connect to cluster with kubectl" kubectl cluster-info

echo "❤ Updating addons scripts"
manifests/addons/addons-update.sh

echo "❤ Creating add-ons "
kubectl create -f manifests/addons
echo "✓ add-on creation success"

echo "❤ Creating busybox test pod "
kubectl create -f test/pods/busybox.yml
[[ $? ]] && echo "✓"

kubectl get no

# ✗
