#!/bin/bash -e

function usage {
  echo "USAGE: $0 <aws-region> <core-os-channel> <coreos-vm-type> <aws-key-name> <internal-tld> <cluster-name> <cidr-allow-ssh> <vpc-cidr> <pod-ip-range> <k8s-service-ip-range> <k8s-service-ip> <k8s-dns-ip> <k8s-etcd-ips> <hyperkube-image> <hyperkube-tag>"
  echo "  example: $0 us-west-1 stable hvm k8s-testing testing.k8s testing 0.0.0.0/0 10.0.0.0/16 10.2.0.0/16 10.3.0.0/24 10.3.0.1 10.3.0.10 10.0.10.10,10.0.10.11,10.0.10.12 quay.io/coreos/hyperkube v1.4.6_coreos.0"

  exit 1
}

if [[ $# -ne 15 ]]; then
  usage
fi

AWS_REGION="$1"
COREOS_CHANNEL="$2"
COREOS_VM_TYPE="$3"
AWS_EC2_KEY_NAME="$4"
INTERNAL_TLD="$5"
CLUSTER_NAME="$6"
CIDR_ALLOW_SSH="$7"
CIDR_VPC="$8"
CIDR_PODS="$9"
CIDR_SERVICE_CLUSTER="${10}"
K8S_SERVICE_IP="${11}"
K8S_DNS_IP="${12}"
ETCD_IPS="${13}"
HYPERKUBE_IMAGE="${14}"
HYPERKUBE_TAG="${15}"

COREOS_AMI_ID=`curl -s \
  $(printf "http://%s.release.core-os.net/amd64-usr/current/coreos_production_ami_%s_%s.txt" \
    $COREOS_CHANNEL $COREOS_VM_TYPE $AWS_REGION)`

AWS_ACCOUNT_ID=`aws iam get-user --output json \
	| awk '/arn:aws:/{print $2}' \
	| grep -Eo '[[:digit:]]{12}'`

AWS_REGION_AZS=`aws ec2 describe-availability-zones --region ${AWS_REGION} --output json \
  | jq --raw-output '.AvailabilityZones | map(.ZoneName) | .[]' \
  | xargs \
  | sed -e 's/ /,/g'`


cat <<EOF > terraform.tfvars
# Generated by scripts/init-variables.sh
aws = {
  account-id = "${AWS_ACCOUNT_ID}"
  azs = "${AWS_REGION_AZS}"
  key-name = "${AWS_EC2_KEY_NAME}"
  region = "${AWS_REGION}"
}
cidr = {
  allow-ssh = "${CIDR_ALLOW_SSH}"
  pods = "${CIDR_PODS}"
  service-cluster = "${CIDR_SERVICE_CLUSTER}"
  vpc = "${CIDR_VPC}"
}
coreos-aws = {
  ami = "${COREOS_AMI_ID}"
  channel = "${COREOS_CHANNEL}"
  type = "${COREOS_VM_TYPE}"
}
k8s = {
    hyperkube-image = "${HYPERKUBE_IMAGE}"
    hyperkube-tag = "${HYPERKUBE_TAG}"
}
dns-service-ip = "${K8S_DNS_IP}"
internal-tld = "${INTERNAL_TLD}"
k8s-service-ip = "${K8S_SERVICE_IP}"
name = "${CLUSTER_NAME}"
s3-bucket = "${AWS_ACCOUNT_ID}-${CLUSTER_NAME}-${AWS_REGION}"
etcd-ips = "$ETCD_IPS"
EOF
if [ -f ./vpc-existing.tfvars ]; then cat ./vpc-existing.tfvars >>terraform.tfvars ; fi
cat terraform.tfvars
