#!/bin/bash -eu

CLUSTER_DOMAIN=$(terraform output cluster-domain)
DNS_SERVICE_IP=$(terraform output dns-service-ip)
INTERNAL_TLD=$(terraform output internal-tld)

OUTDIR=.addons


echo "❤ Patching addon scripts "

[ -d ${OUTDIR} ] || mkdir ${OUTDIR}
cp manifests/addons/* ${OUTDIR}

sed -i.bak 's|${CLUSTER_DOMAIN}|'"${CLUSTER_DOMAIN}|g" "${OUTDIR}/"*.tpl
sed -i.bak 's|${DNS_SERVICE_IP}|'"${DNS_SERVICE_IP}|g" "${OUTDIR}/"*.tpl
sed -i.bak 's|${INTERNAL_TLD}|'"${INTERNAL_TLD}|g" "${OUTDIR}/"*.tpl

for file in ${OUTDIR}/*.tpl
  do mv "${file}" ${file/.tpl/}
done

rm -f .addons/*.bak

echo "✓ Patching add-on scripts success"

# ✗
