#!/bin/bash -eu

CLUSTER_DOMAIN=$(terraform output cluster-domain)
DNS_SERVICE_IP=$(terraform output dns-service-ip)
INTERNAL_TLD=$(terraform output internal-tld)
REGION=$(terraform output region)
WORKER_ASG_NAME=$(terraform output worker-autoscaling-group-name)

OUTDIR=.addons

[ -d ${OUTDIR} ] || mkdir ${OUTDIR}
cp manifests/addons/* ${OUTDIR}

sed -i.bak 's|${CLUSTER_DOMAIN}|'"${CLUSTER_DOMAIN}|g" "${OUTDIR}/"*.tpl
sed -i.bak 's|${DNS_SERVICE_IP}|'"${DNS_SERVICE_IP}|g" "${OUTDIR}/"*.tpl
sed -i.bak 's|${REGION}|'"${REGION}|g" "${OUTDIR}/"*.tpl
sed -i.bak 's|${WORKER_ASG_NAME}|'"${WORKER_ASG_NAME}|g" "${OUTDIR}/"*.tpl

for file in ${OUTDIR}/*.tpl
  do mv "${file}" ${file/.tpl/}
done

rm -f .addons/*.bak

# ✗
