#!/bin/bash -eu

echo "cluster: $CLUSTER_NAME, region: $AWS_REGION"

KZ8S="Name=tag:kz8s,Values=$CLUSTER_NAME"

( \
  printf "instance-id state name role kz8s private-ip public-ip\n" ;\
  aws ec2 describe-instances \
    --output text \
    --filters "Name=instance-state-name,Values=running" $KZ8S \
    --query 'Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key==`Name`].Value|[0],Tags[?Key==`role`].Value|[0],Tags[?Key==`kz8s`].Value|[0],PrivateIpAddress,PublicIpAddress]' \
    --region $AWS_REGION \
) | column -t
