#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

TACK_ROOT=$(dirname "${BASH_SOURCE}")/..

print_red() {
  printf '%b' "\033[91m$1\033[0m\n"
}

print_green() {
  printf '%b' "\033[92m$1\033[0m\n"
}

render_template() {
  eval "echo \"$(cat "$1")\""
}
