#!/bin/bash -eu

ELB=$(terraform output external-elb)

_retry() {
  [ -z "${2}" ] && return 1
  echo -n ${1}
  until printf "." && "${@:2}" &>/dev/null; do sleep 5.2; done; echo "✓"
}

echo "❤ Polling for cluster life - this could take a minute or more"

_retry "❤ Waiting for DNS to resolve for ${ELB}" ping -c1 "${ELB}"
_retry "❤ Curling apiserver external elb" curl --insecure --silent "https://${ELB}"
_retry "❤ Trying to connect to cluster with kubectl" kubectl cluster-info

_retry "❤ Waiting for kube-system namespace" kubectl get namespace kube-system
set -x
# kubectl create namespace kube-system
# kubectl get namespaces
# kubectl get secrets
# kubectl --namespace=kube-system get secrets
# kubectl get serviceaccounts
kubectl cluster-info

# SA=$(kubectl --namespace=kube-system get serviceaccount default -o go-template="{{with index .secrets 0}}{{.name}}{{end}}")
# kubectl --namespace=kube-system delete secret $SA

# sleep 100
