#!/bin/bash -u

WATCH=watch

command -v ${WATCH} &> /dev/null
if [ $? -ne 0 ]; then
  printf "not going to 'watch' pods - cannot find 'watch' program, try: \n\n$ brew install watch\n\n"
  printf "here is the pod status as of now:\n\n"
  kubectl get po --all-namespaces
  exit 0
fi

${WATCH} -n 1 kubectl get pods --all-namespaces &
WATCH_PID=$!

function finish {
  [ -z ${WATCH_PID} ] || kill ${WATCH_PID}
}
trap finish EXIT

until [ `kubectl get po --all-namespaces | grep -v Running | wc -l` -eq 1 ]
  do sleep 2
done

sleep 2
