apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: kube-cert-manager-pvc
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2

